version: '2.3'
# TODO password passed during container build step?
services:
    db:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        networks:
            - frontend
            - backend
        expose:
            - 9200
            - 9300
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - es_data:/usr/share/elasticsearch/data
        healthcheck:
          test: ["CMD", "curl","-u","elastic:$ELASTIC_PASSWORD", "localhost:9200"]
          interval: 30s
          timeout: 5s
          retries: 10
    kibana:
        image: docker.elastic.co/kibana/kibana-x-pack:6.2.3
        networks:
            - frontend
        expose:
            - 5061
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        depends_on:
            db:
                condition: service_healthy
    nginx:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - frontend
        ports:
            - 1234:80
networks:
    frontend:
    backend:
volumes:
    es_data:
